#%RAML 0.8
---
title: 3PS-DAX-INT
version: 1.0
baseUri: http://localhost:8080/api
documentation:
  - title: 3PS-DAX Integration.
    content: |
      3PS-DAX Integration API
/DAXOnboarding:
  displayName: 3ps-dax-integration
  post:
    description: DAX Onboarding
    body:
      application/json:
        schema: !include schemas/partner-profile-schema.json
        example: !include examples/if1-3ps-mule-post-example.json
    responses:
      200:
        description: |
          Request Acknowledged
        body:
          application/json:
            example: |
              {
                "status": "ACK"
              }
/partnerProfileProcessing/v1/partnerProfile:
  /{partnerProfileId}:
    displayName: update partner
    uriParameters:
      partnerProfileId:
        description: partner profile id
        type: string
    get:
      description: Retrieves the partner profile from 3PS to be updated (HARNESS)
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/partner-profile-schema.json
              example: !include examples/if1-3ps-mule-post-example.json
    post:
      description: update partner (Enriched partner profile with DAX response submitted)
      body:
        application/json:
          schema: !include schemas/partner-profile-schema.json
          example: !include examples/if1-3ps-mule-post-example.json
      responses:
        200:
          description: |
            update partner successful
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS"
                }
/partnerProfileProcessing/v1/partnerProfile/recover:
    displayName: 3ps recovered and process all the 3ps partner profile update response from the integration layer when 3ps was down.
    get:
      description: Process all the 3ps partner profile update response when 3ps was down.
      responses:
        200:
          description: |
            Processed successfully
          body:
            application/json:
              example: |
                {
                  "status": "OK"
                }          