#%RAML 0.8
---
title: 3PS-DAX-INT
version: 1.0
baseUri: http://localhost:8080/api
documentation:
  - title: 3PCS-DAX Integration.
    content: |
      This sample API has been created as part of your APIkit project. It is located in src/main/api. Feel free to poke around.
/3ps-dax-int:
  displayName: 3ps-dax-integration
  post:
    description: json payload from 3ps
    body:
      application/json:
        schema: !include schemas/partner-profile-schema.json
        example: !include examples/if1-3ps-mule-post-example.json
    responses:
      200:
        description: |
          Request Acknowledged
        body:
          application/json:
            example: |
              {
                "status": "ACK"
              }