#%RAML 0.8
---
title: 3PS-DAX-INT
version: 1.0
baseUri: http://localhost:8080/api
documentation:
  - title: 3PCS-DAX Integration.
    content: |
      This sample API has been created as part of your APIkit project. It is located in src/main/api. Feel free to poke around.
/3ps-dax-int:
  displayName: 3ps-dax-integration
  post:
    description: create partner
    body:
      application/json:
        schema: !include schemas/partner-profile-schema.json
        example: !include examples/if1-3ps-mule-post-example.json
    responses:
      200:
        description: |
          Request Acknowledged
        body:
          application/json:
            example: |
              {
                "status": "ACK"
              }
/partnerProfileProcessing/v1/partnerProfile:
  /{partnerProfileId}:
    displayName: update partner
    uriParameters:
      partnerProfileId:
        description: partner profile id
        type: string
    get:
      description: Retrieves the partner profile to be updated
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/partner-profile-schema.json
              example: !include examples/if1-3ps-mule-post-example.json
    post:
      description: update partner (Enriched parnter profile with DAX response submitted)
      body:
        application/json:
          schema: !include schemas/partner-profile-schema.json
          example: !include examples/if1-3ps-mule-post-example.json
      responses:
        200:
          description: |
            update partner successful
          body:
            application/json:
              example: |
                {
                  "status": "SUCCESS"
                }