package com.bhnetwork.integration.transformer;

import org.mule.api.MuleMessage;
import org.mule.api.transformer.TransformerException;
import org.mule.api.transport.PropertyScope;
import org.mule.transformer.AbstractMessageTransformer;
import org.tempuri.UPCSubGroupTableServiceCreateRequest;

import com.bhnetwork.integration.pppstodax.canonical.Division;
import com.bhnetwork.integration.pppstodax.canonical.PartnerProfile;
import com.bhnetwork.integration.pppstodax.canonical.Product;
import com.bhnetwork.integration.pppstodax.canonical.SubstitutionGroup;
import com.microsoft.schemas.dynamics._2008._01.documents.upcsubgrouptable.AxdEntityBhnUPCSubGroupTable1;
import com.microsoft.schemas.dynamics._2008._01.documents.upcsubgrouptable.AxdEnumNoYes;
import com.microsoft.schemas.dynamics._2008._01.documents.upcsubgrouptable.AxdUPCSubGroupTable;

public class CanonicalToUPCSubGroupTableServiceCreateRequest extends
		AbstractMessageTransformer {

	@Override
	public Object transformMessage(MuleMessage message, String outputEncoding)
			throws TransformerException {
		UPCSubGroupTableServiceCreateRequest req = new UPCSubGroupTableServiceCreateRequest();
		AxdUPCSubGroupTable upcSubGroupTable = new AxdUPCSubGroupTable();
		
		Division division = ((PartnerProfile) message.getPayload()).getCompany().getCpDivision().get(0);
		//System.out.println("=====================================================");
		//System.out.println("Number of products in canonical: " + division.getProducts().size());
		//System.out.println("=====================================================");
		int idx=0;
		SubstitutionGroup substitutionGroup;
		// BUG in DATA MAPPER
		// we are passing 2 divisionProducts and canon says it has 3 products !!!
		// so when we iterate we get a NPE on the last element
		
		for(Product product: division.getProducts()) {
			//System.out.println("BEFORE getting substitutionGroup #" + idx + " ...");
			if (idx < division.getProducts().size()-1) {
				substitutionGroup = (SubstitutionGroup) product.getSubstGrp();
				//System.out.println("current substitutionGroup(: " + idx + "): " + substitutionGroup.toString());
				
				AxdEntityBhnUPCSubGroupTable1 bhnUPCSubGroupTable1 = new AxdEntityBhnUPCSubGroupTable1();
				
				bhnUPCSubGroupTable1.setBhnDivisionCode(division.getDivisionCode());

				bhnUPCSubGroupTable1.setCardDisplayDesc(substitutionGroup.getSubstitutionCardDisplayDesc());
				// TODO: MerchRecordNumber not in canonical yet
				// what is a good value?
				bhnUPCSubGroupTable1.setMerchRecordNumber("DEFAULT");

				// this is working for single element
				bhnUPCSubGroupTable1.setName("DEFAULT");
				// for multiple elements we need to grab this from the source (json)
				// for now, mapping brand denom desc in both name and brandDenomDesc
				substitutionGroup.setSubstitutionBrandDenomDescription(substitutionGroup.getSubstitutionBrandDenomDescription());
				bhnUPCSubGroupTable1.setName(substitutionGroup.getSubstitutionBrandDenomDescription());
				bhnUPCSubGroupTable1.setPartnerProfileId(message.getProperty("partnerProfileId", PropertyScope.SESSION).toString());
				bhnUPCSubGroupTable1.setPOGCategory1(substitutionGroup.getSubstitutionPOG1Category());
				bhnUPCSubGroupTable1.setPOGCategory2(substitutionGroup.getSubstitutionPOG2Category());
				bhnUPCSubGroupTable1.setPOGCategory3(substitutionGroup.getSubstitutionPOG3Category());
				bhnUPCSubGroupTable1.setPOGDimension(substitutionGroup.getSubstitutionPOGDimension());
				bhnUPCSubGroupTable1.setPortalDisplayName(substitutionGroup.getSubstitutionPortalDisplayName());
				bhnUPCSubGroupTable1.setShipperUPC(AxdEnumNoYes.NO);//TODO currently defaulted to NO as per spec. Will have to revisit it once we get JSON sample value.
				bhnUPCSubGroupTable1.setSubGroupId(substitutionGroup.getSubGroupId());
				bhnUPCSubGroupTable1.setClazz("entity");
				
				// what's a good value?
				bhnUPCSubGroupTable1.setRecId(1234L);
				// what's a good value?
				bhnUPCSubGroupTable1.setRecVersion(123456789);
				
				upcSubGroupTable.getBhnUPCSubGroupTable1().add(bhnUPCSubGroupTable1);
				//System.out.println("AFTER getting substitutionGroup #" + idx + " ...");
				substitutionGroup=null;
			}
			//else
			//	System.out.println("skipping final product (zombie element generated by DM)");
			
			idx++;
		}
		req.setUPCSubGroupTable(upcSubGroupTable);
		return req;
	}
}
